development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: catalog_development
  pool: 5
  username: postgres
  password: 123

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: catalog_test
  pool: 5
  username: postgres
  password: 123

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: catalog_production
  pool: 5
  username: postgres
  password: 123